version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - maven_verify # run below-defined mvn clean verify job

jobs:
  maven_verify:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - run: mvn clean verify

