version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - deploy
        requires:
          - maven/test

jobs:
  deploy:

    docker:
      - image: circleci/openjdk:11.0.1-jdk

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            mvn clean deploy -Dmaven.test.skip=true -s .circleci/settings.xml
